---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
data:
  CLUSTER_ID: 2e76eb6f-ee40-41e0-9233-9cb5e90a24e8
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ENABLE_LIMITED_CACHE: "false"
  ALLOW_CLUSTER_ACCESS: "true"
